<a href="https://colab.research.google.com/github/DavideScassola/torch-dcr/blob/main/examples/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `torch-dcr` Example Notebook

In this Notebook we will show how to use the `torch-dcr` library to compute the DCR (Distance to the Closest Representative) for a given dataset.

First, let's load the Adult dataset:

In [70]:
import pandas as pd

url = "https://raw.githubusercontent.com/rolester/AzureMLModelExplain/master/Adult%20Census%20Income%20Binary%20Classification%20dataset.csv"
df = pd.read_csv(url)
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

As you can notice, the dataset has both categorical and numerical features.

In [71]:
df.dtypes

age                int64
 workclass           str
 fnlwgt            int64
 education           str
 education-num     int64
 marital-status      str
 occupation          str
 relationship        str
 race                str
 sex                 str
 capital-gain      int64
 capital-loss      int64
 hours-per-week    int64
 native-country      str
 income              str
dtype: object

As an example we compute the DCR for the first 1000 rows of the dataset, against the remaining rows. 
In particular, we will compute the 3 nearest neighbors for each row, and we will return both distances and the indexes of the nearest neighbors.

In [72]:
from torch_dcr import dcr

source_df = df.iloc[:1_000]
target_df = df.iloc[len(source_df) :]

dcr_df, indexes_df = dcr(
    source_df=source_df,
    target_df=target_df,
    output_indexes=True,
    k=3,
    metric="l1",
    device="cpu",
    batch_size=100,
)

100%|██████████| 10/10 [00:01<00:00,  8.36it/s]

In [73]:
dcr_df

        dcr_1     dcr_2     dcr_3
0    0.762691  0.916912  1.715632
1    1.406879  1.776078  2.086295
2    0.546455  0.598226  0.791285
3    2.428469  2.772885  3.123858
4    4.367369  4.491842  4.939900
..        ...       ...       ...
995  0.338886  0.614836  0.993005
996  1.153055  1.267150  2.559261
997  3.833781  4.225593  4.270716
998  0.727091  0.771957  0.789884
999  1.881772  2.283470  2.409022

[1000 rows x 3 columns]

In [74]:
indexes_df

     index_1  index_2  index_3
0        112     9527    17774
1       9966     1528     1483
2      25125    30900    22791
3      18178    29119    29185
4      29173    12361     6304
..       ...      ...      ...
995    14095     4985    13956
996    21434     4283     2444
997     5007     9953    22589
998    19192    21802     7748
999    30688     6906     8730

[1000 rows x 3 columns]